{"name": "Test Valid Credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Username field not found", "trace": "self = <paraBank_test.TestParaBank object at 0x000001F693BD9F30>\n\n    @pytest.mark.login\n    @allure.title(\"Test Valid Credentials\")\n    @allure.description(\"Logs in with valid credentials and verifies that the account overview is visible.\")\n    def test_valid_login(self):\n>       self.pb.valid_login()\n\ntestcases\\paraBank_test.py:80: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\paraBank_page.py:137: in valid_login\n    raise e\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.paraBank_page.ParaBankPage object at 0x000001F693D51A90>\n\n    @allure.step(\"Login using username and password\")\n    def valid_login(self):\n        try:\n            username_field = self.get_element(self.Locators.VALID_USERNAME)\n            password_field = self.get_element(self.Locators.VALID_PASSWORD)\n    \n>           assert username_field is not None, \"Username field not found\"\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^\nE           AssertionError: Username field not found\n\npages\\paraBank_page.py:122: AssertionError"}, "description": "Logs in with valid credentials and verifies that the account overview is visible.", "steps": [{"name": "Login using username and password", "status": "failed", "statusDetails": {"message": "AssertionError: Username field not found\n", "trace": "  File \"C:\\vsCode\\parabank_credentials\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\vsCode\\parabank_credentials\\pages\\paraBank_page.py\", line 137, in valid_login\n    raise e\n  File \"C:\\vsCode\\parabank_credentials\\pages\\paraBank_page.py\", line 122, in valid_login\n    assert username_field is not None, \"Username field not found\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "attachments": [{"name": "Login Failure Screenshot", "source": "e9454ef6-5c3a-4d7b-92f1-ad7fd57bfc09-attachment.png", "type": "image/png"}], "start": 1751156513252, "stop": 1751156525347}], "attachments": [{"name": "screenshot", "source": "382ecb4d-1c80-4d87-b1f2-191f37117bc5-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "35d0eea3-cbd3-4047-a385-56cc09d07080-attachment.txt", "type": "text/plain"}], "start": 1751156513251, "stop": 1751156525350, "uuid": "ea08dabb-b3ff-44a3-be61-960afb4f837d", "historyId": "b02c000aaec4e3b1734b87abde7050f5", "testCaseId": "b02c000aaec4e3b1734b87abde7050f5", "fullName": "testcases.paraBank_test.TestParaBank#test_valid_login", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "paraBank_test"}, {"name": "subSuite", "value": "TestParaBank"}, {"name": "host", "value": "Hans"}, {"name": "thread", "value": "3020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.paraBank_test"}]}